name: SonarQube Analysis

on:
  pull_request:
    branches: [develop]
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    uses: rohanht/sonarqube/.github/workflows/sonarqube-analysis.yaml@main
    with:
      project-key: "sonarqube"
      node-version: "18"
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
